### ISSUE TITLE
add_to_mem fails in arm.

### ISSUE THREAD

**Issue by astewart-bah** [angr/angrop#74]
### Description

add_to_mem does not seem to support arm binaries. 

https://github.com/angr/angrop/blob/9099dc3ccce4bf71706e6a88f908482babddde1c/angrop/chain_builder/mem_changer.py#L44

never finds any possible gadgets in 32 bit arm.

### Steps to reproduce the bug

Included is a zip file. Extract the zip file and run start_old.sh. This will set up a python venv and install requirements. start_old will use angrop 9.2.8. It will run a python script that will fetch the Ubuntu i386 libc and Ubuntu armel libc. Then it then attempt to produce example add_to_mem chains with both. 

the i386 chain will print as follows:
```
This is for i386:
Note how calling add_to_mem() succeeds.
code_base = 0x0
chain = b""
chain += p32(code_base + 0x193127)	# neg eax; pop edi; pop ebx; ret 
chain += p32(0xdeadbe92)
chain += p32(0xcafebabe)
chain += p32(code_base + 0x14f2a7)	# add dword ptr [edi + 0x5d], ebx; ret 
```

The armel chain will fail as follows:

```
This is the armel chain.
Note how calling add_to_mem() fails.
Traceback (most recent call last):
  File "/test_old.py", line 67, in <module>
    breakpoint()
  File ".venv_old/lib/python3.10/site-packages/angrop/chain_builder/__init__.py", line 367, in add_to_mem
    raise RopException("Couldnt set registers for any memory add gadget")
angrop.errors.RopException: Couldnt set registers for any memory add gadget

```

[angrop_issue_74.zip](https://github.com/angr/angrop/files/14150066/angrop_issue_74.zip)

**Comment by Kyle-Kyle** [comment]
The root cause is that we our `add_to_mem` implementation was optimized for x86/x64 and assumed that a memory adding gadget has to contain a memory read and memory write in the same instruction.
By rewriting the memory access merging algorithm (how to merge a read and a write into a memory change operation), now `add_to_mem` works on arm.
The test case is integrated into CI as well.
The fix is here: https://github.com/angr/angrop/pull/75/commits/dfe40d4e2103b7e67328fb1c0b63449151032bef
and here https://github.com/angr/angrop/pull/75/commits/fc299a4c10a4dcaabec7983284425d15cd726bd3

**Comment by Kyle-Kyle** [comment]
also, notice that in your case, most part of the libc is in fact in thumb mode. So, you might want to enable`is_thumb`.
